jenkins:
  systemMessage: "UI Automation CI/CD with Docker + Selenium Grid"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID:-admin}"
          password: "${JENKINS_ADMIN_PASSWORD:-admin123}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "${JENKINS_URL:-http://localhost:8090/}"
